services:
  app:
    build: .
    container_name: order_packing_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_ADDRESS: redis:6379
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_order_packing
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "123456"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456

volumes:
  redis_data:
