definitions:
  pack.AddPackSizeRequest:
    properties:
      size:
        type: integer
    required:
    - size
    type: object
  pack.CalculatePackResponse:
    properties:
      packs:
        additionalProperties:
          type: integer
        type: object
    type: object
  pack.GetPackSizesResponse:
    properties:
      sizes:
        items:
          type: integer
        type: array
    type: object
  pack.RemovePackSizeRequest:
    properties:
      size:
        type: integer
    required:
    - size
    type: object
  response.ApiResponseNoData:
    properties:
      error:
        type: string
      message:
        type: string
      status_code:
        type: integer
      success:
        type: boolean
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/packs/calculate:
    get:
      consumes:
      - application/json
      description: Calculates an optimal pack combination using orderItemQuantity
        as query param
      parameters:
      - description: Number of items to order
        format: int64
        in: query
        name: orderItemQuantity
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pack.CalculatePackResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
      summary: Calculate a new pack by order-items
      tags:
      - packs
  /api/v1/packs/sizes:
    delete:
      consumes:
      - application/json
      description: Removes a pack size from the Redis sorted set
      parameters:
      - description: Pack size to remove
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pack.RemovePackSizeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
      summary: Remove a pack size
      tags:
      - packs
    get:
      description: Returns all available pack sizes from Redis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pack.GetPackSizesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
      summary: Get all pack sizes
      tags:
      - packs
    post:
      consumes:
      - application/json
      description: Adds a new pack size to the Redis sorted set
      parameters:
      - description: Pack size to add
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pack.AddPackSizeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponseNoData'
      summary: Add a new pack size
      tags:
      - packs
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
